describe('Can register', function() {
  it('return QRCode', function() {
    cy.visit('http://localhost:3000')
    cy.get('form').scrollIntoView()
    cy.get('[name="name"]')
      .type('Fakename', { force: true })
      .should('have.value', 'Fakename')
    cy.get('[name="lastname"]')
      .type('Fakelastname', { force: true })
      .should('have.value', 'Fakelastname')
    cy.get('[name="email"]')
      .type('fake@email.gg', { force: true })
      .should('have.value', 'fake@email.gg')
    cy.get('form > :nth-child(17)').click({ force: true })
    cy.get('.btn').click({ force: true })
    cy.wait(500)
    cy.get('#regtxt').should('be.visible')
    cy.get('canvas').should('be.visible')
  })
})
